<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Animata.Core/Animata.Core.csproj" />
    <PackageReference Include="HelixToolkit.Avalonia.SharpDX" Version="3.1.2" />
  </ItemGroup>
</Project>
